#!/bin/sh
set -eu
# Providers may start the container with a restrictive umask.
umask 0027
: "${APP_KEY:?APP_KEY must be configured}"
# Never migrate on startup: deployments run migrations once, before rollout.
php artisan config:cache
php artisan route:cache
php artisan view:cache
# Recusar subir com migration pendente: servir um schema antigo com código novo
# produz erro 500 nas telas afetadas, e falhar aqui deixa a causa visível no deploy.
php artisan app:assert-database-ready
# Apache workers must own the caches generated by the root startup process.
chown -R www-data:www-data storage bootstrap/cache
chmod -R u=rwX,g=rX,o= storage bootstrap/cache
exec "$@"
